name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

  build-container:

    runs-on: ubuntu-latest

    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false

    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v3
            
      - name : Setup MPI
        uses: mpi4py/setup-mpi@v1
      
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        
      - name: Setup Singularity
        run : | 
          sudo apt-get update 
          sudo apt-get install -y \
          autoconf \
          automake \
          cryptsetup \
          git \
          libfuse-dev \
          libglib2.0-dev \
          libseccomp-dev \
          libtool \
          pkg-config \
          runc \
          squashfs-tools \
          squashfs-tools-ng \
          uidmap \
          wget \
          zlib1g-dev

      - name: Install Singularity
        run: |
          eexport VERSION=4.1.3 && \
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz && \
          tar -xzf singularity-ce-${VERSION}.tar.gz && \
          cd singularity-ce-${VERSION} 
      
      - name: Build Singularity Container
        run: |
          sudo singularity build container.sif Singularity.def

      - name: Run the Singularity container
        run: ./container.sif 
        
      - name: exec the Singularity container
        run: singularity exec container.sif echo "Hello, Singularity!"
      
      - name: Install sshpass
        run: | 
          sudo apt update
          sudo apt install sshpass
        
        