name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

  build-container:

    runs-on: ubuntu-latest

    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false

    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v3
        
      - name: SSHPASS Github Action
        uses: matheusvanzan/sshpass-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          run: |
            echo "Hello, SSH!"
  
      - name : Setup MPI
        uses: mpi4py/setup-mpi@v1

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        
      - name: Setup Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      
      - name: Build Singularity Container
        run: sudo singularity build --fakeroot container.sif Singularity.def

      - name: Run the Singularity container
        run: sudo ./container.sif 

      - name: exec the Singularity container
        run: singularity exec container.sif echo "Hello, Singularity!"
      
        
        